# Generated by Django 4.1.4 on 2022-12-10 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import docspace.app.core.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=docspace.app.core.models.pdf_path)),
                ('text', models.TextField(blank=True, null=True)),
                ('clean_text', models.TextField(blank=True, null=True)),
                ('info', models.JSONField(default=dict)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_processed', models.DateTimeField(blank=True, null=True)),
                ('upload_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('chunk_index', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('clean_text', models.TextField(blank=True, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document')),
            ],
        ),
    ]
