# Generated by Django 3.2.14 on 2022-12-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chunk_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='text_array',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
