# Generated by Django 3.2.14 on 2022-12-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chunk_text_array'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chunk',
            old_name='text_array',
            new_name='summary_array',
        ),
    ]
