# Generated by Django 3.2.14 on 2022-12-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_text_array_chunk_summary_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
