# Generated by Django 3.2.14 on 2022-12-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chunk_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='cluster',
        ),
    ]
