# Generated by Django 3.2.14 on 2022-12-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cluster'),
        ),
    ]
