# Generated by Django 3.2.14 on 2022-12-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cluster_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='title',
        ),
    ]
