# Generated by Django 3.2.14 on 2022-12-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chunk_similar_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
