# Generated by Django 3.2.14 on 2022-12-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_document_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='cluster_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
